### ISSUE TITLE
Youtube is not working with latest version of youtube-dl 2015.01.02 in GAE

### ISSUE THREAD

**Issue by ksy5662** [jaimeMF/youtube-dl-api-server#24]
Here is some logs for you^^
Thanks in advance!!!

2015-01-02 07:42:02.957 /api/info?url=http://www.youtube.com/watch?v=WZlJf7Rlx84 500 2504ms 0kb Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 module=default version=2014-09-19
221.158.56.146 - - [02/Jan/2015:07:42:02 -0800] "GET /api/info?url=http://www.youtube.com/watch?v=WZlJf7Rlx84 HTTP/1.1" 500 674 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" "2015.01.02.ringtube001.appspot.com" ms=2505 cpu_ms=910 cpm_usd=0.000515 app_engine_release=1.9.17 instance=00c61b117c1fe64a3cbb6fda58d48d243065609f
D 2015-01-02 07:42:00.468
[youtube] Setting language
D 2015-01-02 07:42:01.404
[youtube] Confirming age
D 2015-01-02 07:42:01.544
[youtube] WZlJf7Rlx84: Downloading webpage
D 2015-01-02 07:42:01.805
[youtube] WZlJf7Rlx84: Downloading video info webpage
D 2015-01-02 07:42:02.069
[youtube] WZlJf7Rlx84: Extracting video information
D 2015-01-02 07:42:02.699
[youtube] WZlJf7Rlx84: Encrypted signatures detected.
E 2015-01-02 07:42:02.810
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/extractor/youtube.py", line 432, in _extract_signature_function
    cache_spec = self._downloader.cache.load(u'youtube-sigfuncs', func_id)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 63, in load
    cache_fn = self._get_cache_fn(section, key, dtype)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 32, in _get_cache_fn
    self._get_root_dir(), section, '%s.%s' % (key, dtype))
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 25, in _get_root_dir
    return os.path.expanduser(res)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 268, in expanduser
    import pwd
ImportError: No module named pwd
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
E 2015-01-02 07:42:02.811
Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/youtube_dl_server/app.py", line 78, in info
    result = get_videos(url)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/youtube_dl_server/app.py", line 34, in get_videos
    res = ydl.extract_info(url, download=False)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/YoutubeDL.py", line 539, in extract_info
    self.report_error(compat_str(de), de.format_traceback())
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/YoutubeDL.py", line 410, in report_error
    self.trouble(error_message, tb)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/YoutubeDL.py", line 380, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/extractor/youtube.py", line 432, in _extract_signature_function
    cache_spec = self._downloader.cache.load(u'youtube-sigfuncs', func_id)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 63, in load
    cache_fn = self._get_cache_fn(section, key, dtype)
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 32, in _get_cache_fn
    self._get_root_dir(), section, '%s.%s' % (key, dtype))
  File "/base/data/home/apps/s~ringtube001/2014-09-19.378831065144539708/gae/lib/youtube_dl/cache.py", line 25, in _get_root_dir
    return os.path.expanduser(res)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 268, in expanduser
    import pwd
ImportError: No module named pwd
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
Are you sure your are using 2015.01.02? The line from the error message [doesn't contain that code](https://github.com/rg3/youtube-dl/blob/2015.01.02/youtube_dl/cache.py#L24-L25).

**Comment by ksy5662** [comment]
Sorry! Here is correct one.


2015-01-02 17:19:32.196 /api/info?url=http://www.youtube.com/watch?v=WZlJf7Rlx84 500 257ms 0kb Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 module=default version=2015-01-02
221.158.56.146 - - [02/Jan/2015:17:19:32 -0800] "GET /api/info?url=http://www.youtube.com/watch?v=WZlJf7Rlx84 HTTP/1.1" 500 669 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" "2015-01-02.ringtube001.appspot.com" ms=258 cpu_ms=117 cpm_usd=0.000137 app_engine_release=1.9.17 instance=00c61b117c29768132df706595736cf5d5ce44ef
D 2015-01-02 17:19:31.949
[youtube] WZlJf7Rlx84: Downloading webpage
D 2015-01-02 17:19:32.172
[youtube] WZlJf7Rlx84: Extracting video information
E 2015-01-02 17:19:32.194
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/extractor/youtube.py", line 601, in _decrypt_signature
    video_id, player_url, s
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/extractor/youtube.py", line 506, in _extract_signature_function
    cache_spec = self._downloader.cache.load('youtube-sigfuncs', func_id)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 62, in load
    cache_fn = self._get_cache_fn(section, key, dtype)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 31, in _get_cache_fn
    self._get_root_dir(), section, '%s.%s' % (key, dtype))
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 24, in _get_root_dir
    return compat_expanduser(res)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/compat.py", line 222, in compat_expanduser
    import pwd
ImportError: No module named pwd
 (caused by ImportError('No module named pwd',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
E 2015-01-02 17:19:32.194
Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/youtube_dl_server/app.py", line 78, in info
    result = get_videos(url)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/youtube_dl_server/app.py", line 34, in get_videos
    res = ydl.extract_info(url, download=False)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/YoutubeDL.py", line 607, in extract_info
    self.report_error(compat_str(de), de.format_traceback())
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/YoutubeDL.py", line 478, in report_error
    self.trouble(error_message, tb)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/YoutubeDL.py", line 448, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/extractor/youtube.py", line 601, in _decrypt_signature
    video_id, player_url, s
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/extractor/youtube.py", line 506, in _extract_signature_function
    cache_spec = self._downloader.cache.load('youtube-sigfuncs', func_id)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 62, in load
    cache_fn = self._get_cache_fn(section, key, dtype)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 31, in _get_cache_fn
    self._get_root_dir(), section, '%s.%s' % (key, dtype))
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/cache.py", line 24, in _get_root_dir
    return compat_expanduser(res)
  File "/base/data/home/apps/s~ringtube001/2015-01-02.381244864196550758/gae/lib/youtube_dl/compat.py", line 222, in compat_expanduser
    import pwd
ImportError: No module named pwd
 (caused by ImportError('No module named pwd',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaimeMF** [comment]
Thanks for the report, fixed in 0.1.2

**Comment by ksy5662** [comment]
Thanks, JaimeMF

Great work!!!
