### ISSUE TITLE
ERROR: "token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by JJGEight** [jaimeMF/youtube-dl-api-server#55]
For every YouTube URL that I try to retrieve the JSON Data, I get the following message. I have also tried the same YouTube URLs on http://jaimemf.github.io/youtube-dl-web/ and an error message is returned. I have tried using YouTube-DL from the command line and I can download the video so I am guessing something is going wrong with the api-server. Unfortunately I am unsure what as I'm new to using this project.

```
{
  "error": "ERROR: VLAXxAoWAok: \"token\" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."
}
```

**Comment by jaimeMF** [comment]
It works fine when using a local server but it fails on GAE even with the last youtube-dl version. Unfortunately I think it would take me some time to look into it in detail, if someone finds a fix I will appreciate it.

**Comment by docsuleman** [comment]
the issue i guess is that youtube has banned GAE ips. i shifted to amazon
web service myself.

**Comment by docsuleman** [comment]
I just tested. IP is not blocked. video_get_info is giving result on a php script on GAE.

**Comment by docsuleman** [comment]
Complete Error 
`Traceback (most recent call last):
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/gae/lib/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/gae/lib/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/youtube_dl_server/app.py", line 65, in wrapper
response = f(*args, **kargs)
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/youtube_dl_server/app.py", line 148, in info
result = get_result()
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/youtube_dl_server/app.py", line 141, in get_result
return get_videos(url, extra_params)
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/youtube_dl_server/app.py", line 36, in get_videos
res = ydl.extract_info(url, download=False)
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/gae/lib/youtube_dl/YoutubeDL.py", line 711, in extract_info
self.report_error(compat_str(e), e.format_traceback())
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/gae/lib/youtube_dl/YoutubeDL.py", line 570, in report_error
self.trouble(error_message, tb)
File "/base/data/home/apps/s~ptube03/0-3.400278601054968939/gae/lib/youtube_dl/YoutubeDL.py", line 540, in trouble
raise DownloadError(message, exc_info)
DownloadError: ERROR: Ktq4zATPFsI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by ocsemp** [comment]
youtube-dl is outdated.

**Comment by Abdullah2993** [comment]
after putting a logging statement before this ` logging.info(str(video_info))` [here ](https://github.com/rg3/youtube-dl/blob/ddbb4c5c3ea7a64e09834d9628e7e34e03675289/youtube_dl/extractor/youtube.py#L1526) I got this
```

2017-06-23 (04:37:36.070)
[2017-06-22 23:37:36,070] ERROR in YoutubeDL: ERROR: 5NPBIwQyPWE: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2017-06-23 (04:37:35.991)
youtube.py:1526
{u'\x1bNs\ufffd\ufffd~5\ufffd\ufffd:{\ufffd\ufffd>L\ufffd\ufffdEM\u05f3\ufffd\ufffdi\ufffdZ\ufffd\ufffd4\ufffd': [u'"\u06d7\ufffd^\ufffd\ufffdM\x1d\x1a\ufffd*U\ufffd\u0692*\x1bp\ufffd\x14\ufffd\x1c\n\ufffd\\hy\ufffd*i`\ufffd\x00\u040dH,\ufffd5\ufffdD\x0f\ufffd\ufffdX\x13\ufffd'], u'\x1b\x01\\D\x14\ufffd\x01P\ufffd\x0cs_\ufffd\ufffd\ufffd\ufffdk\x18<\ufffdM\ufffd\n\x17\ufffd\x1f\ufffdO\ufffd\ufffdx\ufffd\x01\ufffd8\ufffd\r\u6bf5>\ufffd\x01\ufffd\ufffd\x0b\ufffd\ufffd\ufffd\ufffd(\\\ufffd\x0b\xbc\ufffd': [u"\ufffd\ufffdY\ufffd\ufffd\ufffd?\ufffd\ufffd\r,\x1c\ufffdB\x00\ufffdgf'\u0120\ufffd\u61c8\ufffdBPT\x1e\u02d3\u0799\ufffd*\x15E`\ufffdW\ufffd\x13.\x98\ufffd\x18j\u0695\ufffd\ufffd.4F\ufffd\n\ufffd\ufffd\ufffd\u02ab\ufffd"], u'\ufffd\ufffd)\\\ufffd\x0e\x7f\ufffd#mo\ufffdC\ufffdkdH|\u028a\ufffdl\ufffd\x1e\ufffd\ufffd\ufffd\u0608\ufffd\ufffdH\ufffd\u01a1': [u'\ufffd\ufffd\ufffdi\x17\ufffd\x12\ufffd\ufffdJ\ufffdJ\x0f2\x11i\x1f\ufffd\ufffd\ufffd\ufffd\ufffdW\x17?g\ufffd\ufffdy\ufffd]\\^<'], u'\ufffd\ufffdi\ufffd\x1f\ufffd\ufffd2\x03\ufffd\ufffdn': [u'\ufffd\ufffd\x05\ufffd\ufffd0\ufffd7\ufffd\ufffd$M\ufffd\ufffd\u0634\ufffd9\ufffd\ufffd|\ufffd\x12*\ufffd\ufffd\ufffdAj\ufffd\ufffd\u07a8\x06\ufffd\x02.2*\ufffd\ufffdP`\ufffd4\ufffd\ufffd\ufffd\x16 \ufffd~ \x17na\x1a\u06f3G\ufffd\x0f\xfc?\ufffdv\ufffd\ufffd\ufffdu\ufffd\ufffd\u07a8(]\x1b\x0bx\ufffd\ufffdM\ufffdJ\ufffd\x11\uf82ehw<4T\ufffd\ufffd\x13\ufffd\ufffd\x0cq\ufffd\ufffd\ufffdC\ufffd\ufffd'], u'\x13\tQ\ufffdz\x0e\ufffd\ufffd~\ufffd\ufffd\ufffd\ufffd\x00\ufffdyh(4X\x1b\ufffd\ufffd\ufffd|\ufffd\ufffd\ufffd7l\ufffd\ufffd\r\ufffdS\ufffd`\ufffd\ufffd_\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd`}y \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdlxY\uf584\ucbcf\x10\x19\ufffd\t\ufffd\ufffdR': [u'\ufffdl\ufffdg2\x1b\ufffdT\ufffd\ufffd`\ufffdw\ufffdr\ufffd\ufffd#\x12=\ufffd\ufffd\ufffd0\ufffd\ufffd.\ufffdo\ufffd\ufffd\ufffdx^\ufffd\ufffd1\ufffdN\ufffdWc\x0f~\ufffdl\ufffdYL]\ufffd\ufffd\ufffdR\ufffd\ufffd\ufffdl\ufffd\ufffd/w\ufffdw0\ufffdH0u\ufffd=\ufffd\ufffd\ufffd\ufffd\ufffd\u0646\ufffdH\ufffdO\ufffd\ufffdn%f\ufffd~3\ufffd/\u06c6o,\ufffdn]\ufffd\x1c\ufffdL%\ufffd\ufffd\ufffd_tm\ufffd\ufffd\u01ee\ufffdw\r\ufffd@\u01b0wlM\x08w2m\ufffd\ufffd*4X)\ufffd\ufffd\ufffd%\ufffd\ufffda\x0eh\ufffdB\ufffd\x01'], u'\ufffd\ufffdy\ufffdP\ufffdT\ufffd\t\ufffdN\ufffd-\ufffdy\ufffd\ufffd\x1e\ufffd\x18[\ufffd\x00:!S\x0fP\ufffd\ufffdQ\x191V\x0b\x1c\ufffd`\x12!RN6\ufffd\x02\ufffd\ufffd\ufffd\ufffd%%U3BW\ufffdApjrH\ufffd\ufffd\ufffd\x1c$j\ufffd\u022er\x10\ufffd,\ufffd44\x0c\ufffd\x1ab\ufffd\ufffd\x06cH\ufffd_\u05c8\ufffd\x18^--Bj\x18<\ufffdA\x1a(\ufffd\ufffd\x17\ua438:\x18\ufffdeWT\ufffd\x02M|s|p\ufffd\ufffd\ufffd\ufffd\x1c3\x02f\ufffdj\r\ufffdlm\ufffd9FW}\r\ufffd\ufffdy\ufffd\x11e\ufa6e\xa2\x1c\ufffd\x03d\x0b\ufffdO\ufffd\ufffd*Y\x15\ufffdX\x00|\ufffdb\x1bic\ufffd\ufffd\ufffd]\\\ufffd\ufffd\ufffd8\ufffd\ufffd1\ufffd#t\ufffd\ufffd\x1aRV\ufffdB\x03A\ufffd\ufffdB\x1d\x12[\ufffd\ufffd\ufffd!\ufffd': [u'\ufffd\ufffd\u0152<b6\x1c\\\ufffd\ufffdy5\ufffd\ufffdYTDRK\ufffdQ\x0c\ufffdBP?2\ufffd\ufffd\\*5\ufffd\\\x1d\ufffd\ufffd5j\ufffdj\ufffdVp\ufffd\ufffd@N\x0c\x19q1\x0c\x07y\x00t^[\ufffdb\ufffd\ufffd\u03dc9\ufffd\x01z\x0c\x0f\ufffd\ufffdD\ufffd/\ufffdJi \ufffdq_\ufffd\ufffd1u0dM B\ufffd\u0668\ufffdtfa\ufffd\x00$\x03\ufffd\x06KWO\u0380M'], u"A{\u03f5\x0e\u07b7\x18\ufffdWK\ufffd8CBq\x01\x11O\ufffd\x04c\ufffdvIy\ufffd\ufffdSKif\ufffd[4q\x1744\ufffdI\x07\ufffd\ufffdY\ufffd\u06a5\ufffdU\x19\ufffd\ufffdV\ufffdC\ufffdZp\ufffd3\u047a\u96b6\ufffd\ufffd\ufffd\ufffdNC\ufffd:\ufffdH{\ufffdo\ufffd\x03}\ufffdt~L\ufffd8` \ufffd\ufffd\x14\u05b0\r\ufffdv8l\ufffdg\ufffd\u04e7}:\uce85'\ufffd\ufffd\x0fs\ufffd\x13\ufffd4\ufffd\ufffd \ufffd\ufffd\ufffd\ufffdk\ufffd\nfc\ufffd-\x01'6\ufffd\ufffdX\x1b\ufffd\ufffd\t\x12u\ufffd`6H\ufffd\x00\x1e.\x0e7\x1bN?s\ufffd\ufffd\ufffd\ubfcf\x1f\ufffd\u07d7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdOo ": [u'\ufffd\ufffd\ufffd\ufffd'], u'\ufffdS6\x04\ufffd6U\ufffd\ufffd\x12\ufffd\x08J,\ufffdG\ufffdQ!E\x03\x1clr\ufffd\ufffd\ufffd\ufffd\x03\ufffd\ufffdk\x02q\ufffdbl\ufffdl\x18': [u'\ufffd^\ufffdY\ufffdE!\ufffd\x07\ufffd\x01\ufffdK\ufffd\x1cVf\ufffd\ufffdh@\ufffdl\t<\ufffd\ufffd\x02e\ufffdP\x07c\ufffd`\ufffd2\x1e\ufffd0\x1c\ufffdY-\ufffd7\ufffd\ufffdE]@P\ufffd\ufffd\ufffd\ufffd3\x12-\ufffd\\\ufffds\x18}\ufffd1\x044L\ufffd\ufffdGT\ufffd:\ufffd\ufffdVJ\x19\ufffd\ufffd\ufffd1X\ufffd\x03T/\x15\x1a\ufffd\x04\ufffdm>*\x115\ufffd\ufffd\ufffd)35\x11(K\ufffd\x00m\x03\x0fdk\u0450\x14=0\x02\ufffd\ufffdX\ufffd\ufffd]\ufffd\ufffdqu0\ufffd\ufffd\u078d\ufffd'], u"QQ\ufffd\ufffd*/\x11\ufffdF\ufffd\x03\ufffd\ufffd\ufffd\ufffdSC\ufffd\ufffd\ufffd,6\ufffdu\ufffd\ufffd\x01\ufffd<`*\ufffdWE\ufffdw\u0176qC\ufffd,lz\ufffd\ufffd\x12\ufffd\x0b\ufffdFL\x1c\u0400w\ufffd:\ufffdP\\g0v,\x18\ufffd\ufffd\ufffd\ufffdpH\x1f\x0f\u01c9r\x1b\ufffd\ufffd\x1f\ufffd\ufffd[\ufffd\ufffd\U00078f1d\u0674\ufffd\ufffdw\ufffd\ufffd'u\ufffdL\x15\ufffd\ufffdu\ufffd\ufffdi\ufffdP`\ufffd\ufffde\ufffd\ufffd\ufffdj(\x1b\ufffd\ufffd\ufffdf\u0690I\ufffd\x13\x15\ufffd\ufffd": [u'i\ufffd.\ufffd\ufffd\ufffdP\ufffdX\ufffd.z\x18\ufffd\ufffd@\ufffd\ufffdI\ufffd\ufffd\ufffd\ufffd7\ufffd\t\ufffd\ufffd}\x1b\u0106jC\ufffd\ufffdD\u0177\ufffd0\ufffd\n\ufffd.>\u05ab\ufffd6'], u'\ufffdc6\ufffdg.P2\ufffd\\\ufffd\u01d4\ufffds\n\x13%\ufffd\ufffdo\x14*\ufffd\ufffd\ufffd\x11\ufffd\ufffd\\Lq\ufffd*VO\ufffd\x1clq\x01D\ufffdMP\ufffd\ufffdM\ufffd%\ufffd\ufffdhh\ufffd\ufffd_< \ufffd\x07\x03\ufffd2\\\ufffd MF\ufffd\x11o\ufffd\ufffd\ufffdN\ufffd\ufffdRw\n\ufffd\ufffd\ufffd\ufffdvwx\x1d\ufffd\ufffd\u04f6': [u'.\ufffd\ufffd\ufffd6\ufffd\ufffd\u010cw\ufffdi\ufffd\x1c\ufffd\ufffd\ufffdk\ufffd\ufffd\ufffd\ufffd\ufffd3\ufffdWT\ufffd\ufffd<\x1b2d_Y\ufffd\ufffd}\x13Q\ufffd\ufffdhH\ufffd1\x07\ufffdW\x11.\ufffd\x05tG\u74c4\ufffd\ufffdf\ufffda\ufffd\ufffd_\ufffdYABZI\ufffd\ufffd-\x1c5,!\ufffd\x15\u05b0\x11\x00F\x14a*I\ufffd']}
```

**Comment by docsuleman** [comment]
may be  video_info data is compressed.? gziped?
